const API_URL = '3.128.26.53:8080'

export const LOGIN_ENDPOINT = API_URL + '/users/login'
export const REGISTER_ENDPOINT = API_URL + '/users'
export const PUBLIC_POSTS_ENDPOINT = API_URL + '/posts/last'
export const POST_DETAILS_ENDPOINT = API_URL + '/posts'
export const USERS_POSTS_ENDPOINT = API_URL + '/users/posts'
export const CREATE_POST_ENDPOINT = API_URL + '/posts'
export const DELETE_POST_ENDPOINT = API_URL + '/posts'
export const UPDATE_POST_ENDPOINT = API_URL + '/posts'
